# Docker Compose configuration for Prong C++20 UI Framework
# Provides convenient development workflow with reproducible build environment

services:
  # Base build service for library-only builds
  builder:
    image: prong-builder:latest
    build:
      context: .
      target: builder
      cache_from:
        - prong-builder:latest
    volumes:
      # Mount source code
      - .:/workspace
      # Use named volume for build artifacts to improve performance
      - build-cache:/workspace/build
      # Cache mise installations for faster container startup
      - mise-cache:/root/.cache/mise
    working_dir: /workspace
    command: bash
    stdin_open: true
    tty: true
    environment:
      # Suppress locale warnings (optional)
      - LANG=C
      - LC_ALL=C

  # Service for building examples (includes GLFW and OpenGL)
  examples:
    image: prong-examples:latest
    build:
      context: .
      target: examples-builder
      cache_from:
        - prong-builder:latest
        - prong-examples:latest
    volumes:
      - .:/workspace
      - build-cache:/workspace/build
      - mise-cache:/root/.cache/mise
    working_dir: /workspace
    command: bash
    stdin_open: true
    tty: true
    environment:
      - LANG=C
      - LC_ALL=C
      # For X11 forwarding (optional, for running examples)
      - DISPLAY=${DISPLAY:-:0}
    # Uncomment for GPU passthrough and X11 forwarding
    # devices:
    #   - /dev/dri:/dev/dri
    # volumes:
    #   - /tmp/.X11-unix:/tmp/.X11-unix:ro

volumes:
  # Named volume for build artifacts
  build-cache:
  # Named volume for mise cache
  mise-cache:
